
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3098:3098"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "4590:4590"
    depends_on:
      - nextjs
