services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "4589:4589"
    depends_on:
      - nextjs
